// Shared client-domain types + pure helpers used by BOTH server actions
// (which import `apiFetch` from `@/lib/api/client`, which pulls in
// server-only `@clerk/nextjs/server`) and client components (which must
// not). Kept in its own module — same pattern as `staff-days.ts`.
//
// If you need to add an API call, put it in `@/lib/api/clients.ts` (the
// server-only file) and have it re-export the type from this file. Don't
// add fetch/auth imports here.

// ---- Enums ----

export type ClientIntakeStatus = 'pending' | 'sent' | 'completed' | 'expired';

// ---- Tag projection ----

export type ClientTagSummary = {
  id: string;
  name: string;
  color: string | null;
};

// ---- Client row shape (mirror of API's CLIENT_SAFE_FIELDS) ----

export type Client = {
  id: string;
  tenantId: string;
  // Per-tenant sequential client number; render as `CL-{6-digit padded}`
  // via the formatClientNumber helper. Generated by the API on create.
  clientNumber: number;
  firstName: string;
  lastName: string | null;
  email: string | null;
  phone: string | null;
  dateOfBirth: string | null;
  addressLine1: string | null;
  addressLine2: string | null;
  city: string | null;
  state: string | null;
  postalCode: string | null;
  country: string | null;
  emergencyContactName: string | null;
  emergencyContactPhone: string | null;
  intakeStatus: ClientIntakeStatus;
  notes: string | null;
  // Tier A — communication preferences + banned flag.
  smsOptedOut: boolean;
  emailOptedOut: boolean;
  preferredChannel: string;
  banned: boolean;
  bannedReason: string | null;
  bannedAt: string | null;
  createdAt: string;
  updatedAt: string;
  deletedAt: string | null;
  // List + detail responses both include the tag projection.
  tags: ClientTagSummary[];
};

// Detail endpoint augments Client with tagIds. List rows OMIT this.
export type ClientWithTags = Client & { tagIds: string[] };

// ---- Write body / duplicate-warning shapes (used by the form too) ----

export type DuplicateWarning = {
  matchedByEmail: number;
  matchedByPhone: number;
  matchIds: string[];
};

export type ClientWriteBody = {
  firstName: string;
  lastName?: string;
  email?: string;
  phone?: string;
  dateOfBirth?: string;
  addressLine1?: string;
  addressLine2?: string;
  city?: string;
  state?: string;
  postalCode?: string;
  country?: string;
  emergencyContactName?: string;
  emergencyContactPhone?: string;
  intakeStatus?: ClientIntakeStatus;
  notes?: string;
  tagIds?: string[];
};

// ---- Stats response (E3-S7) ----

export type AppointmentSummaryStat = {
  appointmentId: string;
  scheduledStartAt: string;
  scheduledEndAt: string;
  state: string;
  staffId: string;
  staffName: string | null;
  serviceId: string;
  serviceName: string | null;
};

export type ClientStats = {
  totalVisits: number;
  totalCompletedVisits: number;
  totalCancelledVisits: number;
  totalNoShowVisits: number;
  lastVisit: AppointmentSummaryStat | null;
  upcomingAppointment: AppointmentSummaryStat | null;
  totalNotes: number;
  totalAlertNotes: number;
  totalFiles: number;
  memberSince: string;
};

// ---- Client tier — derived from stats (E3-S7) ----
//
// Single source of truth for the "what kind of client are they" badge
// that appears next to the name in both admin and staff profile views.
// Threshold values are intentional and not yet tenant-configurable:
//   - First-time   = no completed visits yet
//   - Lapsed       = haven't visited in 90+ days
//   - Regular      = 5+ visits and active (visited within 90 days)
//   - Active       = visited within 90 days but fewer than 5 lifetime
//   - VIP threshold tracked in pre-launch sweep for tenant configurability
export type ClientTier =
  | 'first_time'
  | 'active'
  | 'regular'
  | 'lapsed';

const NINETY_DAYS_MS = 90 * 24 * 60 * 60 * 1000;
const REGULAR_THRESHOLD = 5;

export function deriveClientTier(stats: ClientStats): ClientTier {
  if (stats.totalCompletedVisits === 0 && stats.totalVisits === 0) {
    return 'first_time';
  }
  const last = stats.lastVisit?.scheduledStartAt;
  if (!last) return 'first_time';
  const daysSinceLast = Date.now() - new Date(last).getTime();
  if (daysSinceLast > NINETY_DAYS_MS) return 'lapsed';
  return stats.totalVisits >= REGULAR_THRESHOLD ? 'regular' : 'active';
}

export const CLIENT_TIER_LABELS: Record<ClientTier, string> = {
  first_time: 'First-time',
  active: 'Active',
  regular: 'Regular Client',
  lapsed: 'Lapsed',
};

export const CLIENT_TIER_TONES: Record<
  ClientTier,
  'neutral' | 'accent' | 'amber' | 'green'
> = {
  first_time: 'accent',
  active: 'green',
  regular: 'green',
  lapsed: 'amber',
};

// ---- Media response (E3-S7) ----
// `import type` for MediaAsset — the type-only import is erased at
// compile time so this module stays free of any runtime imports from
// `lib/api/media`, which is server-only-tainted via apiFetch.
import type { MediaAsset } from './api/media';

export type ClientMediaResponse = {
  referencePhotos: MediaAsset[];
  intakeDocs: MediaAsset[];
  consentDocs: MediaAsset[];
  receipts: MediaAsset[];
  generated: MediaAsset[];
};

// ---- Pure helpers ----

// Format a clientNumber for display. Mirrors the API-side helper in
// `apps/api/src/services/clientService.ts`.
export function formatClientNumber(n: number): string {
  return `CL-${String(n).padStart(6, '0')}`;
}
